parent_config_to_override: "_base_static_harmful_cot.yaml"
run_name: "007_niki_kto_cot_motivated"

# Trajectory generation settings
iterations: 10

# Influence model settings
veto_prompt_type: "five_point"

# NOTE: this failed with an error about "raise ValueError("No objects to concatenate")"
